//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by foo_discord_rich.rc
//
#define IDD_PREFS_MAIN_TAB              107
#define IDD_PREFS_TAB_HOST              116
#define IDD_PREFS_ADVANCED_TAB          121
#define IDD_CTX_MENU_INPUT              123
#define IDD_PREFS_ARTWORK_TAB           125
#define IDD_PREFS_UPLOADER_TAB          126
#define IDC_TEXTBOX_DETAILS             1068
#define IDC_TEXTBOX_STATE               1069
#define IDC_TEXTBOX_PARTYID             1070
#define IDC_RADIO_IMG_LIGHT             1071
#define IDC_RADIO_IMG_DARK              1072
#define IDC_RADIO_IMG_DISABLED          1073
#define IDC_RADIO_TIME_PROGRESS_BAR     1074
#define IDC_RADIO_TIME_ELAPSED          1075
#define IDC_RADIO_TIME_DISABLED         1076
#define IDC_CHECK_IS_ENABLED            1077
#define IDC_TAB1                        1078
#define IDC_TEXTBOX_LARGE_LIGHT_ID      1079
#define IDC_TEXTBOX_LARGE_DARK_ID       1080
#define IDC_TEXTBOX_SMALL_PLAYING_LIGHT_ID 1081
// 1082 FREE
#define IDC_TEXTBOX_SMALL_PLAYING_DARK_ID 1083
#define IDC_TEXTBOX_SMALL_PAUSED_LIGHT_ID 1084
#define IDC_TEXTBOX_SMALL_PAUSED_DARK_ID 1085
#define IDC_TEXTBOX_APP_TOKEN           1086
#define IDC_RADIO_PLAYBACK_IMG_LIGHT    1087
#define IDC_RADIO_PLAYBACK_IMG_DARK     1088
#define IDC_RADIO_PLAYBACK_IMG_DISABLED 1089
#define IDC_CHECK_DISABLE_WHEN_PAUSED   1090
#define IDC_CHECK_SWAP_STATUS           1091
#define IDC_LINK_FORMAT_HELP            1092
#define IDC_TEXTBOX_ARTWORK_COMMAND     1094
#define IDC_CHECK_UPLOAD_ARTWORK        1095
#define IDC_TEXTBOX_METADB_KEY          1096
#define IDC_TEXTBOX_URL                 1097
#define IDC_TEXTBOX_PROCESS_TIMEOUT     1098
#define IDC_RADIO_STATUS_NAME           1099
#define IDC_RADIO_STATUS_TOP            1100
#define IDC_RADIO_STATUS_MIDDLE         1101
#define IDC_TEXTBOX_BLUR_PERCENT        1102
#define IDC_TEXTBOX_HIDDEN_PLACEHOLDER_URL 1103
#define IDC_CHECK_OVERRIDE_ARTWORK_URL  1104
#define IDC_TEXTBOX_ARTWORK_OVERRIDE_URL 1105
#define IDC_RADIO_UPLOADER_MODE_BUNDLED 1106
#define IDC_RADIO_UPLOADER_MODE_CUSTOM_COMMAND 1107
#define IDC_COMBO_BUNDLED_UPLOADER_SERVICE 1108
#define IDC_TEXTBOX_BUNDLED_UPLOADER_API_KEY 1109
#ifndef IDC_STATIC
#define IDC_STATIC -1
#endif

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        127
#define _APS_NEXT_COMMAND_VALUE         40012
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
